### ISSUE TITLE
TODO Organizer side

### ISSUE THREAD

**Issue by thyjukki** [thyjukki/tipubot#1]
- [ ] Set tipu date and time
- [ ] Set phone number
- [ ] Set price, default to 1 euro
- [ ] Set description
- [ ] Organizer reminder
- [ ] Set winner
- [ ] Override organizer
