### ISSUE TITLE
TODO General

### ISSUE THREAD

**Issue by thyjukki** [thyjukki/tipubot#2]
- [ ] Chat reminder
- [ ] List current participants
- [ ] Previous raffle history
- [ ] Generate payment link

**Comment by viitana** [comment]
Regarding payment links, it seems mobilepay a has more direct payment URL scheme in the format
`mobilepayfi://send?phone=somePhoneNumber&amount=someEuroAmount&comment=someURLEncodedCommentText`

E.g. On mobile the standard payment link
`https://www.mobilepay.fi/Yrityksille/Maksulinkki/maksulinkki-vastaus?phone=123456789&amount=1&comment=Huutista`
will have a button for opening the MobilePay app directly and prefilling the respective fields that points to
`mobilepayfi://send?phone=123456789&amount=1&comment=Huutista`

I wasn't able to trigger the MobilePay app to open by linking with the above URL sceme directly in Telegram as Telegram doesn't recognize it as a valid URL, but it could be doable using [HTML formatting ](https://core.telegram.org/bots/api#formatting-options)with a bot.

**Comment by OGChef** [comment]
> I wasn't able to trigger the MobilePay app to open by linking with the above URL sceme directly in Telegram as Telegram doesn't recognize it as a valid URL, but it could be doable using [HTML formatting ](https://core.telegram.org/bots/api#formatting-options)with a bot.

TG doesn't like non-HTTP links. The easiest way is to just slap the mobilepayfi:// link to tinyurl.com or a similar service and then put that into the bot. Works fine and security issues are not really an issue since the bot could tell the user to "always check if the recipient is Tipu Rigger" or something
